-- =========================================================
-- MART: REVENUE COHORT ANALYSIS
-- =========================================================
-- Description: Track revenue generated by each cohort over time
-- Sources: stg_orders, stg_payments, stg_customers
-- Destination: olist_marts.mart_revenue_cohort
-- Granularity: Cohort month + months since cohort
-- =========================================================

CREATE OR REPLACE TABLE `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort` AS

WITH customer_cohorts AS (
  SELECT 
    customer_id,
    DATE_TRUNC(MIN(order_purchase_timestamp), MONTH) AS cohort_month
  FROM `quintoandar-ecommerce-analysis.olist_staging.stg_orders`
  WHERE is_completed = TRUE
  GROUP BY customer_id
),

cohort_sizes AS (
  SELECT
    cohort_month,
    COUNT(DISTINCT customer_id) AS cohort_size
  FROM customer_cohorts
  GROUP BY cohort_month
),

order_revenue_cohorts AS (

  SELECT 
    o.order_id,
    o.customer_id,
    c.cohort_month,
    DATE_TRUNC(o.order_purchase_timestamp, MONTH) AS order_month,
    o.order_purchase_timestamp,
    p.payment_value,
    
    DATE_DIFF(
      DATE_TRUNC(o.order_purchase_timestamp, MONTH),
      c.cohort_month,
      MONTH
    ) AS months_since_cohort
    
  FROM `quintoandar-ecommerce-analysis.olist_staging.stg_orders` o
  INNER JOIN `quintoandar-ecommerce-analysis.olist_staging.stg_payments` p
    ON o.order_id = p.order_id
  INNER JOIN customer_cohorts c
    ON o.customer_id = c.customer_id
  WHERE o.is_completed = TRUE
),

cohort_monthly_revenue AS (

  SELECT
    cohort_month,
    order_month,
    months_since_cohort,
    
    SUM(payment_value) AS cohort_revenue,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS active_customers,
    
    AVG(payment_value) AS avg_order_value,
    SUM(payment_value) / COUNT(DISTINCT customer_id) AS revenue_per_active_customer
    
  FROM order_revenue_cohorts
  GROUP BY cohort_month, order_month, months_since_cohort
),

cohort_cumulative AS (

  SELECT
    cmr.*,
    cs.cohort_size,
    
    SUM(cmr.cohort_revenue) OVER (
      PARTITION BY cmr.cohort_month 
      ORDER BY cmr.months_since_cohort
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_revenue,
    
    SUM(cmr.cohort_revenue) OVER (
      PARTITION BY cmr.cohort_month 
      ORDER BY cmr.months_since_cohort
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) / cs.cohort_size AS cumulative_revenue_per_customer,
    
    cmr.active_customers / cs.cohort_size AS active_customer_rate,
    
    cmr.cohort_revenue / cs.cohort_size AS monthly_revenue_per_cohort_customer

  FROM cohort_monthly_revenue cmr
  INNER JOIN cohort_sizes cs
    ON cmr.cohort_month = cs.cohort_month
),

cohort_summary AS (
  SELECT
    cc.*,
    
    CASE 
      WHEN cc.cumulative_revenue_per_customer > (
        SELECT AVG(cumulative_revenue_per_customer) * 1.2 
        FROM cohort_cumulative 
        WHERE months_since_cohort = cc.months_since_cohort
      ) THEN 'High Performing'
      WHEN cc.cumulative_revenue_per_customer < (
        SELECT AVG(cumulative_revenue_per_customer) * 0.8 
        FROM cohort_cumulative 
        WHERE months_since_cohort = cc.months_since_cohort
      ) THEN 'Low Performing'
      ELSE 'Average Performing'
    END AS cohort_performance,
    
    LAG(cc.cohort_revenue, 1) OVER (
      PARTITION BY cc.cohort_month 
      ORDER BY cc.months_since_cohort
    ) AS previous_month_revenue,
    
    CASE 
      WHEN LAG(cc.cohort_revenue, 1) OVER (
        PARTITION BY cc.cohort_month 
        ORDER BY cc.months_since_cohort
      ) > 0 THEN
        (cc.cohort_revenue - LAG(cc.cohort_revenue, 1) OVER (
          PARTITION BY cc.cohort_month 
          ORDER BY cc.months_since_cohort
        )) / LAG(cc.cohort_revenue, 1) OVER (
          PARTITION BY cc.cohort_month 
          ORDER BY cc.months_since_cohort
        ) * 100
      ELSE NULL
    END AS revenue_growth_rate

  FROM cohort_cumulative cc
)

SELECT
  cohort_month,
  order_month,
  months_since_cohort,
  cohort_size,
  cohort_revenue,
  cumulative_revenue,
  total_orders,
  active_customers,
  avg_order_value,
  revenue_per_active_customer,
  cumulative_revenue_per_customer,
  active_customer_rate,
  monthly_revenue_per_cohort_customer,
  cohort_performance,
  previous_month_revenue,
  revenue_growth_rate
FROM cohort_summary
ORDER BY cohort_month DESC, months_since_cohort ASC;


/*
-- VALIDATION QUERIES
-- 1. Total revenue by cohort (best/worst performers)
SELECT
  cohort_month,
  cohort_size,
  SUM(cohort_revenue) AS total_cohort_revenue,
  MAX(cumulative_revenue_per_customer) AS max_ltv,
  ROUND(AVG(cumulative_revenue_per_customer), 2) AS avg_ltv,
  CASE
    WHEN SUM(cohort_revenue) / cohort_size > (
      SELECT AVG(SUM(cohort_revenue) / cohort_size) 
      FROM cohort_summary 
      GROUP BY cohort_month
    ) THEN 'Above Average'
    ELSE 'Below Average'
  END AS performance_category
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
GROUP BY cohort_month, cohort_size
ORDER BY total_cohort_revenue DESC;

-- 2. Cohort retention analysis over time
SELECT
  months_since_cohort,
  COUNT(DISTINCT cohort_month) AS cohorts_observed,
  ROUND(AVG(active_customer_rate) * 100, 2) AS avg_retention_rate_pct,
  ROUND(AVG(cumulative_revenue_per_customer), 2) AS avg_ltv,
  ROUND(AVG(monthly_revenue_per_cohort_customer), 2) AS avg_monthly_value
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
WHERE months_since_cohort <= 12
GROUP BY months_since_cohort
ORDER BY months_since_cohort;

-- 3. Monthly revenue trends across cohorts
SELECT
  order_month,
  COUNT(DISTINCT cohort_month) AS active_cohorts,
  SUM(cohort_revenue) AS total_monthly_revenue,
  SUM(active_customers) AS total_active_customers,
  ROUND(SUM(cohort_revenue) / SUM(active_customers), 2) AS revenue_per_active_customer
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
GROUP BY order_month
ORDER BY order_month;

-- 4. Best performing cohorts analysis
SELECT
  cohort_month,
  cohort_size,
  total_cohort_revenue,
  max_ltv,
  avg_ltv,
  performance_category
FROM (
  SELECT
    cohort_month,
    cohort_size,
    SUM(cohort_revenue) AS total_cohort_revenue,
    MAX(cumulative_revenue_per_customer) AS max_ltv,
    ROUND(AVG(cumulative_revenue_per_customer), 2) AS avg_ltv,
    CASE
      WHEN SUM(cohort_revenue) / cohort_size > (
        SELECT AVG(SUM(cohort_revenue) / cohort_size) 
        FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
        GROUP BY cohort_month
      ) THEN 'Above Average'
      ELSE 'Below Average'
    END AS performance_category
  FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
  GROUP BY cohort_month, cohort_size
)
ORDER BY avg_ltv DESC
LIMIT 10;

-- 5. Cohort revenue matrix (cohort month vs months since cohort)
SELECT
  cohort_month,
  MAX(CASE WHEN months_since_cohort = 0 THEN cohort_revenue ELSE 0 END) AS month_0_revenue,
  MAX(CASE WHEN months_since_cohort = 1 THEN cohort_revenue ELSE 0 END) AS month_1_revenue,
  MAX(CASE WHEN months_since_cohort = 2 THEN cohort_revenue ELSE 0 END) AS month_2_revenue,
  MAX(CASE WHEN months_since_cohort = 3 THEN cohort_revenue ELSE 0 END) AS month_3_revenue,
  MAX(CASE WHEN months_since_cohort = 6 THEN cohort_revenue ELSE 0 END) AS month_6_revenue,
  MAX(CASE WHEN months_since_cohort = 12 THEN cohort_revenue ELSE 0 END) AS month_12_revenue
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`
GROUP BY cohort_month
ORDER BY cohort_month DESC;

-- 6. Data quality and completeness check
SELECT
  'Total Cohorts' AS metric,
  COUNT(DISTINCT cohort_month) AS value
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`

UNION ALL

SELECT
  'Average Cohort Size',
  ROUND(AVG(cohort_size), 0)
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`

UNION ALL

SELECT
  'Total Revenue Tracked',
  ROUND(SUM(cohort_revenue), 2)
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`

UNION ALL

SELECT
  'Max Months Tracked',
  MAX(months_since_cohort)
FROM `quintoandar-ecommerce-analysis.olist_marts.mart_revenue_cohort`;
*/